/**
 * auto-populate.ts
 *
 * After an athlete is created, this module fires in the background.
 * It calls OpenAI to generate realistic, source-attributed intelligence
 * for the athlete and inserts it across all related tables.
 *
 * Profile photos are sourced from the real Wikipedia API — not AI-generated
 * URLs which are unreliable. If no Wikipedia image exists, avatarUrl is null.
 *
 * The POST /athletes route responds immediately — this runs after the
 * response is sent so the user never waits on it.
 */

import { openai } from "@workspace/integrations-openai-ai-server";
import { db } from "@workspace/db";
import { logger } from "./logger.js";
import { adjustConfidenceByDomain } from "./source-validation.js";
import { runCompetitionsAgent } from "./competitions-agent.js";
import { runContactsAgent } from "./contacts-agent.js";
import { runTimelineAgent } from "./timeline-agent.js";
import { runSponsorsAgent } from "./sponsors-agent.js";
import { runSocialProfilesAgent } from "./social-profiles-agent.js";
import { runSocialMetricsAgent } from "./social-metrics-agent.js";
import { runBiographyAgent } from "./biography-agent.js";
import { runPhotoAgent } from "./photo-agent.js";
import { runIntelligenceAgent } from "./intelligence-agent.js";
import { runResultsAgent } from "./results-agent.js";
import { withAiConcurrencyLimit } from "./ai-concurrency.js";
import { withRetry } from "./retry.js";
import type { AthleteStub } from "./athlete-stub.js";
import {
  athletesTable,
  intelligenceItemsTable,
  timelineEventsTable,
  contactsTable,
  competitionsTable,
} from "@workspace/db";
import { eq } from "drizzle-orm";

// Twitter/X real follower lookup moved to social-metrics-agent.ts (M9).
// Photo lookup moved to photo-agent.ts (M10), which wraps the existing
// Wikipedia-first hierarchy in ./photo-lookup.ts (still shared with admin
// backfill) as its fallback after trying federation sources first.
// General research + rank/PB/SB extraction moved to results-agent.ts (M12)
// — the last content generated by the original monolithic prompt.

/**
 * Minimum confidence score (0–100) required to accept a discovery result.
 * Below this threshold the athlete cannot be uniquely identified from their
 * name alone and the creation request is rejected with HTTP 422.
 */
export const DISCOVERY_CONFIDENCE_THRESHOLD = 70;

/**
 * Given only an athlete's name, call OpenAI to identify their sport, event,
 * nationality, approximate age, and — critically — how confidently this name
 * maps to a single identifiable individual.
 *
 * Confidence scale:
 *   90–100  Unambiguous: one uniquely identifiable well-known athlete
 *   70–89   Confident: not a common name, GPT has meaningful knowledge of this person
 *   50–69   Uncertain: multiple athletes share this name, or athlete is obscure
 *   < 50    No identification possible: very common name or completely unknown
 *
 * Returns null for sport/nationality when they cannot be determined, so the
 * caller can detect and reject an incomplete identity rather than silently
 * defaulting to "Athletics" / "".
 */
export async function discoverAthleteProfile(name: string): Promise<{
  sport: string | null;
  event: string | null;
  nationality: string | null;
  age: number | null;
  confidence: number;
  ambiguous: boolean;
  reason: string;
}> {
  const response = await withAiConcurrencyLimit(() =>
    withRetry(
      () =>
        openai.chat.completions.create({
          model: "gpt-4o",
          max_completion_tokens: 512,
          messages: [
            {
              role: "system",
              content: `You are a sports data assistant. Given an athlete's name, identify the specific individual and return a JSON object.

Return ONLY valid JSON, no markdown. Fields:
- sport: their primary sport as a string, or null if you cannot determine it
- event: their specific event or position, or null if unknown
- nationality: their country name, or null if you cannot determine it
- age: approximate age as an integer, or null if unknown
- confidence: integer 0-100 — how confident you are that this name maps to ONE specific identifiable athlete:
    90-100: unambiguous, one uniquely identifiable well-known athlete
    70-89:  confident, not a very common name and you have real knowledge of this person
    50-69:  uncertain, multiple athletes share this name or this person is not well-known
    0-49:   cannot identify, very common name or no sports association found
- ambiguous: boolean — true if multiple athletes share this name across different sports or countries
- reason: one sentence explaining your confidence assessment`,
            },
            {
              role: "user",
              content: `Athlete name: "${name}"\n\nReturn: { "sport": string|null, "event": string|null, "nationality": string|null, "age": integer|null, "confidence": integer, "ambiguous": boolean, "reason": string }`,
            },
          ],
          response_format: { type: "json_object" },
        }),
      { label: "discoverAthleteProfile" },
    ),
  );

  const raw = response.choices[0]?.message?.content;
  if (!raw) throw new Error("Empty response from OpenAI");

  const data = JSON.parse(raw);
  return {
    sport:       typeof data.sport       === "string"  ? data.sport       : null,
    event:       typeof data.event       === "string"  ? data.event       : null,
    nationality: typeof data.nationality === "string"  ? data.nationality : null,
    age:         typeof data.age         === "number"  ? data.age         : null,
    confidence:  typeof data.confidence  === "number"  ? Math.min(100, Math.max(0, Math.round(data.confidence))) : 0,
    ambiguous:   typeof data.ambiguous   === "boolean" ? data.ambiguous   : true,
    reason:      typeof data.reason      === "string"  ? data.reason      : "Could not assess confidence.",
  };
}

export async function autoPopulateAthlete(athlete: AthleteStub): Promise<void> {
  try {
    // Phase 1: every field is now sourced from its own dedicated retrieval
    // agent (ResultsAgent M12, CompetitionsAgent M4, ContactsAgent M5,
    // TimelineAgent M6, SponsorsAgent M7, SocialProfilesAgent M8,
    // BiographyAgent + PhotoAgent M10, IntelligenceAgent M11) — each owns
    // its own full research+extraction+validation cycle and never throws,
    // so one agent's research failing degrades only its own field rather
    // than discarding every other agent's already-validated results.
    const [results, avatarUrl, competitionRows, contactsResult, timelineRows, sponsorRows, socialHandles, biography, intelligenceRowsFromAgent] = await Promise.all([
      runResultsAgent(athlete),
      runPhotoAgent(athlete),
      runCompetitionsAgent(athlete),
      runContactsAgent(athlete),
      runTimelineAgent(athlete),
      runSponsorsAgent(athlete),
      runSocialProfilesAgent(athlete),
      runBiographyAgent(athlete),
      runIntelligenceAgent(athlete),
    ]);

    // Phase 2: SocialMetricsAgent (M9) needs socialHandles from Phase 1.
    const socialMetrics = await runSocialMetricsAgent(athlete, socialHandles);

    // ── 1. Update athlete stats + verified photo ────────────────────────────
    await db
      .update(athletesTable)
      .set({
        // ResultsAgent (M12) — rank/PB/SB, already PB<=SB cross-validated.
        worldRank: results.worldRank,
        worldRankDelta: results.worldRankDelta,
        nationalRank: results.nationalRank,
        personalBest: results.personalBest,
        seasonBest: results.seasonBest,
        // BiographyAgent (M10) — only overwrites age/nationality when
        // confidently confirmed by fresh research; null means "no
        // update", not "unknown" (see biography-agent.ts).
        age: biography.age ?? undefined,
        nationality: biography.nationality ?? undefined,
        // Handles: SocialProfilesAgent (M8). Follower counts:
        // SocialMetricsAgent (M9) — real X API for Twitter, handle-
        // matched Perplexity fallback for Instagram/TikTok. Written as
        // whatever this run found -- a number if verified, null if not.
        // Never coerced to 0: unknown must stay unknown (M14 fix for the
        // M13 audit's Problem #2).
        instagramHandle: socialHandles.instagramHandle,
        instagramFollowers: socialMetrics.instagramFollowers,
        twitterHandle: socialHandles.twitterHandle,
        tiktokHandle: socialHandles.tiktokHandle,
        tiktokFollowers: socialMetrics.tiktokFollowers,
        twitterFollowers: socialMetrics.twitterFollowers,
        // avatarUrl: PhotoAgent (M10) — federation-first, falls back to
        // the existing Wikipedia hierarchy. Not AI-generated.
        avatarUrl: avatarUrl ?? null,
        hasNewIntelligence: true,
        lastCrawledAt: new Date(),
      })
      .where(eq(athletesTable.id, athlete.id));

    // ── 2. Intelligence items (IntelligenceAgent's general categories +
    //      SponsorsAgent's sponsorship items — both already fully
    //      validated by their own agents, merged into one insert/count) ────
    const intelligenceRows = [...intelligenceRowsFromAgent, ...sponsorRows].map((row) => ({
      athleteId: athlete.id,
      athleteName: athlete.name,
      category: row.category,
      title: row.title,
      summary: row.summary,
      sourceDomain: row.sourceDomain,
      sourceUrl: row.sourceUrl,
      confidence: row.confidence,
      publishedAt: row.publishedAt,
    }));
    if (intelligenceRows.length > 0) {
      await db.insert(intelligenceItemsTable).values(intelligenceRows);
      await db
        .update(athletesTable)
        .set({ intelligenceCount: intelligenceRows.length, hasNewIntelligence: true })
        .where(eq(athletesTable.id, athlete.id));
    }

    // ── 3. Timeline events (from TimelineAgent — dates, duplicates, and
    //      source attribution already validated before this point) ─────────
    if (timelineRows.length > 0) {
      const rows = timelineRows.map((ev) => ({
        athleteId: athlete.id,
        date: ev.date,
        category: ev.category,
        title: ev.title,
        description: ev.description,
        location: ev.location,
        sourceDomain: ev.sourceDomain,
        sourceUrl: ev.sourceUrl,
        confidence: ev.confidence,
        significant: ev.significant,
      }));
      await db.insert(timelineEventsTable).values(rows);
    }

    // ── 4. Contacts (from ContactsAgent — garbage already filtered, evidence
    //      already cross-checked against real citations before this point) ──
    if (contactsResult.contacts.length > 0) {
      const rows = contactsResult.contacts.map((c) => ({
        athleteId: athlete.id,
        role: c.role,
        category: c.category,
        name: c.name,
        org: c.org,
        orgType: c.orgType,
        status: c.status,
        confidence: c.confidence,
        publicEmail: c.publicEmail,
        website: c.website,
        note: c.note,
        lastVerified: c.lastVerified,
        dateDiscovered: c.dateDiscovered,
        sourceDomain: c.sourceDomain,
        sourceExcerpt: c.sourceExcerpt,
      }));
      await db.insert(contactsTable).values(rows);
    }

    // ── 5. Competitions (from CompetitionsAgent — generic meet names already
    //      filtered out before this point) ───────────────────────────────────
    if (competitionRows.length > 0) {
      const rows = competitionRows.map((comp) => ({
        athleteId: athlete.id,
        athleteName: athlete.name,
        meetName: comp.meetName,
        event: comp.event,
        location: comp.location,
        date: comp.date,
        tier: comp.tier,
        status: comp.status,
        result: comp.result,
      }));
      await db.insert(competitionsTable).values(rows);
    }

    logger.info(
      { athleteId: athlete.id, name: athlete.name, hasPhoto: !!avatarUrl },
      "auto-populate: completed successfully",
    );
  } catch (err) {
    // Every retrieval agent (ResultsAgent M12 onward) catches its own
    // research/extraction failures internally and never throws — a
    // rejection reaching here means a database write failed after the
    // agents already produced their results. Partial data may have been
    // written; admin retry will overwrite with fresh data. Stamp
    // lastCrawledAt so the scheduler doesn't immediately re-queue this
    // athlete on the next cycle — give it ~1 day before retrying.
    try {
      await db
        .update(athletesTable)
        .set({ lastCrawledAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000) }) // 6 days ago → retries in ~1 day
        .where(eq(athletesTable.id, athlete.id));
    } catch {
      // ignore — best-effort
    }
    logger.error(
      { err, athleteId: athlete.id, name: athlete.name },
      "auto-populate: failed during database write",
    );
  }
}

// adjustConfidenceByDomain moved to source-validation.ts (M5) so agent
// modules like contacts-agent.ts can use it without importing this file
// and creating a circular dependency. Re-exported here for compatibility.
export { adjustConfidenceByDomain };

/**
 * Wipes all existing intelligence data for an athlete, resets their crawl
 * marker, and fires a fresh auto-populate run in the background.
 *
 * This is the single authoritative implementation of the repopulate workflow.
 * Both POST /athletes/:id/repopulate and POST /admin/repopulate/:id delegate
 * here, ensuring identical behaviour regardless of which surface triggered
 * the crawl.
 *
 * The function always fetches the full athlete row itself so that every field
 * (including event and age) is available to the research pipeline — callers
 * should not need to pass athlete data.
 *
 * If the athlete no longer exists by the time this runs (race condition after
 * a 404 check passes), the function logs and returns cleanly; the 202 was
 * already sent to the caller.
 */
export async function repopulateAthlete(athleteId: number): Promise<void> {
  // Fetch the full athlete row so the research pipeline has every field
  // (event, age, etc.). This also guards against race-condition deletions.
  const [athlete] = await db
    .select()
    .from(athletesTable)
    .where(eq(athletesTable.id, athleteId));

  if (!athlete) {
    logger.error({ athleteId }, "repopulate: athlete not found; skipping");
    return;
  }

  // Wipe all existing intelligence data in parallel
  await Promise.all([
    db.delete(intelligenceItemsTable).where(eq(intelligenceItemsTable.athleteId, athleteId)),
    db.delete(timelineEventsTable).where(eq(timelineEventsTable.athleteId, athleteId)),
    db.delete(contactsTable).where(eq(contactsTable.athleteId, athleteId)),
    db.delete(competitionsTable).where(eq(competitionsTable.athleteId, athleteId)),
  ]);

  // Reset crawl marker so the dossier page shows "populating" state
  await db
    .update(athletesTable)
    .set({ intelligenceCount: 0, hasNewIntelligence: false, lastCrawledAt: null })
    .where(eq(athletesTable.id, athleteId));

  // Fire the research pipeline in the background — do not await
  autoPopulateAthlete({
    id:          athlete.id,
    name:        athlete.name,
    sport:       athlete.sport       ?? "",
    event:       athlete.event       ?? "",
    nationality: athlete.nationality ?? "",
    age:         athlete.age,
  }).catch((err) =>
    logger.error({ err, athleteId }, "repopulate: background populate failed"),
  );
}
