/**
 * intelligence-agent.ts
 *
 * IntelligenceAgent — replaces the last content still generated by the
 * shared main-extraction prompt in auto-populate.ts (results_rankings,
 * media_interviews, career_changes intelligence items). Per
 * docs/roadmap.md / docs/ai-architecture.md ("IntelligenceAgent — 3
 * category queries, 8-item minimum").
 *
 * Runs one dedicated research+extraction cycle per category, in
 * parallel, same "N parallel scopes" pattern as ContactsAgent (M5).
 *
 * Reframing applied to "8-item minimum", same as TimelineAgent's (M6)
 * treatment of "20-30 events": the number is an investigative-depth
 * signal (logged when a category falls short), never a target the model
 * is told to pad toward. Some athletes genuinely have more or less
 * newsworthy material in a given category than others — the prompt asks
 * for real, evidenced items only, and the code never invents more to hit
 * a count.
 */

import { openai } from "@workspace/integrations-openai-ai-server";
import { logger } from "./logger.js";
import { callPerplexity } from "./perplexity-client.js";
import { withAiConcurrencyLimit } from "./ai-concurrency.js";
import { withRetry } from "./retry.js";
import { isValidDate } from "./validation.js";
import { resolveSourceAttribution, applyConfidenceFloor } from "./source-validation.js";
import type { AthleteStub } from "./athlete-stub.js";

export type IntelligenceCategory = "results_rankings" | "media_interviews" | "career_changes";

export interface IntelligenceRow {
  category: IntelligenceCategory;
  title: string;
  summary: string | null;
  sourceDomain: string;
  sourceUrl: string | null;
  confidence: number;
  publishedAt: Date;
}

const MIN_ITEM_CONFIDENCE = 70;

/** Per-category count below which the result is logged as possibly sparse, never enforced. */
const INVESTIGATIVE_DEPTH_BENCHMARK = 8;

const CATEGORY_FOCUS: Record<IntelligenceCategory, string> = {
  results_rankings:
    "their competition results, rankings, and ranking changes over their career — specific results with dates, placements, and ranking movements",
  media_interviews:
    "media coverage of them — interviews, features, profile pieces, and notable quotes from journalists or the athlete themselves",
  career_changes:
    "changes in their career — team/club changes, coaching changes, retirement announcements, comebacks, injuries and returns, or other significant career transitions",
};

export function normalizeTitle(title: string): string {
  return title.trim().toLowerCase().replace(/\s+/g, " ");
}

async function researchCategory(
  athlete: AthleteStub,
  category: IntelligenceCategory,
): Promise<{ research: string; citations: string[] }> {
  const today = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
  try {
    const { research, citations } = await callPerplexity({
      label: `intelligence-agent research (${category})`,
      maxTokens: 3072,
      systemPrompt: `You are a sports intelligence researcher. Today's date is ${today}. Be specific — include exact dates, exact details, exact sources. Never fabricate information.`,
      userPrompt: `Research ${athlete.name} (${athlete.sport} — ${athlete.event}, ${athlete.nationality}): ${CATEGORY_FOCUS[category]}

Cover their career from the past 10 years, spread across early, mid, and recent career where the record supports it. Report only real, specific, dated items — do not pad with generic restatements. If there is genuinely little material in this category, report what's real rather than stretching for a count.

Cite your sources.`,
    });
    logger.info(
      { athleteId: athlete.id, name: athlete.name, category, length: research.length, citationCount: citations.length },
      "intelligence-agent: research complete",
    );
    return { research, citations };
  } catch (err) {
    logger.warn(
      { err, athleteId: athlete.id, name: athlete.name, category },
      "intelligence-agent: research failed — skipping this category this run",
    );
    return { research: "", citations: [] };
  }
}

const SYSTEM_PROMPT = (category: IntelligenceCategory): string => `You are a sports intelligence data engine extracting "${category}" items. Return ONLY valid JSON — no markdown, no explanation.

Guiding principle: quality over quantity, evidence over completeness, unknown over invented. You are not trying to hit a target number of items — report as many real, evidenced items as this specific athlete's record genuinely supports.

Rules:
- ACCURACY FIRST: use the provided research as your primary source of truth. Do not contradict it.
- Every item must be grounded in a real, specific claim in the research — not a generic restatement.
- sourceUrl MUST be chosen from the provided CITATION URLs list. If no citation is relevant, set sourceUrl to null. NEVER invent, guess, or construct a URL.
- sourceDomain must match the domain of the chosen sourceUrl, or be the most relevant real domain from the research if sourceUrl is null.
- publishedAt must be an ISO-8601 date reflecting when the item actually occurred or was reported.
- confidence: 85-97 for data explicitly stated in the research. 70-84 for reasonably inferred from context. Never below 70 — omit the item instead if evidence is that weak.`;

const USER_PROMPT = (a: AthleteStub, research: string, citations: string[]): string => `
Athlete: ${a.name} (${a.sport} — ${a.event}, ${a.nationality})

${citations.length > 0
  ? `VERIFIED CITATION URLs — use ONLY these for sourceUrl fields. Do NOT invent URLs.
${citations.map((c, i) => `${i + 1}. ${c}`).join("\n")}

`
  : ""}${research
  ? `VERIFIED RESEARCH:
\`\`\`
${research}
\`\`\``
  : `ABORT: No verified research is available. Return { "items": [] }.`}

Extract as JSON:
{
  "items": [
    {
      "title": <string>,
      "summary": <string, 2-3 sentences with specific details>,
      "sourceDomain": <string>,
      "sourceUrl": <string or null — MUST be from the citation list above, or null>,
      "confidence": <integer 70-97>,
      "publishedAt": <ISO-8601 date>
    }
    // As many real, specific, dated items as the research genuinely supports.
    // Do not pad toward any particular count.
  ]
}
`;

async function extractCategory(
  athlete: AthleteStub,
  category: IntelligenceCategory,
  research: string,
  citations: string[],
): Promise<IntelligenceRow[]> {
  if (!research) return [];

  try {
    const response = await withAiConcurrencyLimit(() =>
      withRetry(
        () =>
          openai.chat.completions.create({
            model: "gpt-4o",
            max_completion_tokens: 2048,
            messages: [
              { role: "system", content: SYSTEM_PROMPT(category) },
              { role: "user", content: USER_PROMPT(athlete, research, citations) },
            ],
            response_format: { type: "json_object" },
          }),
        { label: `intelligence-agent extraction (${category})` },
      ),
    );
    const raw = response.choices[0]?.message?.content;
    if (!raw) return [];

    const data = JSON.parse(raw) as { items?: any[] };
    const rawItems = Array.isArray(data.items) ? data.items : [];

    const rows: IntelligenceRow[] = [];
    const seen = new Set<string>();
    let droppedInvalid = 0;
    let droppedDuplicate = 0;
    let droppedLowConfidence = 0;

    for (const item of rawItems) {
      const title = typeof item?.title === "string" ? item.title.trim() : "";
      if (!title) {
        droppedInvalid++;
        continue;
      }
      const publishedAt = isValidDate(item.publishedAt) ? new Date(item.publishedAt) : null;
      if (!publishedAt) {
        droppedInvalid++;
        continue;
      }
      const dedupeKey = normalizeTitle(title);
      if (seen.has(dedupeKey)) {
        droppedDuplicate++;
        continue;
      }

      const { sourceDomain, sourceUrl } = resolveSourceAttribution(item.sourceUrl, citations);
      const { confidence, passesFloor } = applyConfidenceFloor(item.confidence, sourceDomain, sourceUrl !== null, MIN_ITEM_CONFIDENCE);
      if (!passesFloor) {
        droppedLowConfidence++;
        continue;
      }

      seen.add(dedupeKey);
      rows.push({
        category,
        title,
        summary: item.summary ? String(item.summary) : null,
        sourceDomain,
        sourceUrl,
        confidence,
        publishedAt,
      });
    }

    if (droppedInvalid > 0 || droppedDuplicate > 0 || droppedLowConfidence > 0) {
      logger.warn(
        { athleteId: athlete.id, name: athlete.name, category, droppedInvalid, droppedDuplicate, droppedLowConfidence, kept: rows.length },
        "intelligence-agent: dropped invalid, duplicate, or low-confidence items",
      );
    }
    if (rows.length < INVESTIGATIVE_DEPTH_BENCHMARK) {
      logger.info(
        { athleteId: athlete.id, name: athlete.name, category, count: rows.length, benchmark: INVESTIGATIVE_DEPTH_BENCHMARK },
        "intelligence-agent: category count below the investigative-depth benchmark — may indicate sparse research, not treated as an error",
      );
    }

    return rows;
  } catch (err) {
    logger.warn(
      { err, athleteId: athlete.id, name: athlete.name, category },
      "intelligence-agent: extraction failed — skipping this category this run",
    );
    return [];
  }
}

async function runCategory(athlete: AthleteStub, category: IntelligenceCategory): Promise<IntelligenceRow[]> {
  const { research, citations } = await researchCategory(athlete, category);
  return extractCategory(athlete, category, research, citations);
}

/**
 * Runs the IntelligenceAgent: three parallel category research+extraction
 * cycles, merged into one array. Never throws — a category that fails
 * simply contributes nothing rather than blocking the others.
 */
export async function runIntelligenceAgent(athlete: AthleteStub): Promise<IntelligenceRow[]> {
  const [results, media, career] = await Promise.all([
    runCategory(athlete, "results_rankings"),
    runCategory(athlete, "media_interviews"),
    runCategory(athlete, "career_changes"),
  ]);
  return [...results, ...media, ...career];
}
