/**
 * useAuthFetch — wraps fetch() with a Clerk Bearer token.
 *
 * Use this anywhere you call fetch("/api/...") directly.
 * The react-query hooks generated by Orval are handled separately via
 * setAuthTokenGetter in App.tsx.
 */
import { useAuth } from "@clerk/react";
import { useCallback } from "react";

export function useAuthFetch() {
  const { getToken } = useAuth();

  const authFetch = useCallback(
    async (input: RequestInfo | URL, init: RequestInit = {}): Promise<Response> => {
      const token = await getToken();
      const headers = new Headers(init.headers);
      if (token && !headers.has("authorization")) {
        headers.set("authorization", `Bearer ${token}`);
      }
      return fetch(input, { ...init, headers });
    },
    [getToken],
  );

  return authFetch;
}
