// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/athlete-intelligence/AgentCreation.tsx": () => import("../components/mockups/athlete-intelligence/AgentCreation.tsx"),
  "./components/mockups/athlete-intelligence/AlertConfig.tsx": () => import("../components/mockups/athlete-intelligence/AlertConfig.tsx"),
  "./components/mockups/athlete-intelligence/AthleteFeed.tsx": () => import("../components/mockups/athlete-intelligence/AthleteFeed.tsx"),
  "./components/mockups/athlete-intelligence/Dashboard.tsx": () => import("../components/mockups/athlete-intelligence/Dashboard.tsx"),
  "./components/mockups/athlete-intelligence/Schedule.tsx": () => import("../components/mockups/athlete-intelligence/Schedule.tsx"),
  "./components/mockups/athlete-intelligence/SignIn.tsx": () => import("../components/mockups/athlete-intelligence/SignIn.tsx")
};
